# Generated by Django 4.2.3 on 2023-07-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('entry_number', models.CharField(max_length=20)),
                ('chambre', models.CharField(max_length=50)),
                ('lit', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cin_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=50)),
                ('children_number', models.PositiveIntegerField()),
                ('emergency_contact', models.CharField(max_length=200)),
                ('contact_address', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=20)),
                ('date_of_entry', models.DateField()),
            ],
        ),
    ]
